"""Generate src/data.asm: station layouts and sprite pictures for the Model III port."""
import os as _os, sys as _sys
REPO = _os.path.abspath(_os.path.join(_os.path.dirname(__file__), '..'))
for _d in ('tools', 'tests', 'emulator', '../BigFive-Miner2049/tools', '../BigFive-Miner2049/emulator'):
    if _os.path.join(REPO, _d) not in _sys.path: _sys.path.insert(0, _os.path.join(REPO, _d))

import json
D = json.load(open(_os.path.join(REPO, 'tools/data/m3_stations.json')))
NAMES = ['The Mine Shaft', 'The Slides', 'The Transporters', 'The Lillipads', 'Advanced Lillipads',
         'Radioactive Waste', 'Advanced Transporters', 'The Lift', 'The Pulverizers', 'The Cannon']

# ---- sprites (6 wide; rows written left to right, '#' = lit) --------------------------------
BOB = {
 'STAND': ["..##..", ".#####", "..###.", ".####.", "..##..", "..#.#."],
 'WALK1': ["..##..", ".#####", "..###.", ".####.", "..##..", ".#..#."],
 'WALK2': ["..##..", ".#####", "..###.", ".####.", "..##..", "..##.."],
 'WALK3': ["..##..", ".#####", "..###.", ".####.", "..##..", "#...#."],
 'CLIMB1': ["..##..", ".####.", "#.##.#", ".####.", "..##..", ".#..#."],
 'CLIMB2': ["..##..", ".####.", "..##..", "######", "..##..", "..#..#"],
 'JUMP':  ["..##..", ".#####", "#.###.", ".####.", ".#..#.", "#....#"],
}
MUT = {
 'R1': [".####.", "######", "#.#.#."],
 'R2': [".####.", "######", ".#.#.#"],
 'E1': ["#.##.#", ".####.", ".#..#."],
 'E2': ["#.##.#", "######", "#....#"],
}
def X(px): return (px * 4) // 5
def Ym(y): return 3 + int(round((y - 8) * 44 / 183))
def mirror(rows): return [r[::-1] for r in rows]
def rowbytes(rows): return [int(r.replace('#', '1').replace('.', '0').ljust(8, '0'), 2) for r in rows]

# hand-placed specials (coordinates worked out from the Atari setup code, see the notes)
SPECIALS = {
 6: ['db\t3,16,39,111,46,7\t; box of radioactive waste: x0, y0, x1, y1, tile (deadly)',
     'db\t4,13,29,"DANGER",0\t; text: character row, column',
     'db\t4,14,24,"RADIOACTIVE WASTE",0'],
 8: ['db\t5,89,40,44,89,22,44\t; the lift: x, row, x range, row range'],
 9: ['db\t6,38,32,104,39,44,35,54,73,92\t; pulverizers: beam row, beam x0, x1, head top rows, head x'],
 10: ['db\t3,0,24,41,24,10\t; the TNT store: roof (a row higher than the Atari line, so Bob',
      'db\t3,0,25,0,46,10\t;   fits under it on the top shelf), walls (tile 10 = wall)',
      'db\t3,41,25,41,40,10',
      'db\t3,15,21,15,23,10\t; its sign, under the girder above',
      'db\t3,26,21,26,23,10',
      'db\t4,7,9,"TNT",0',
      'db\t7,90,51,90,29,19,9\t; the cannon: rest x, x range, landing rows for 1-3 tons'],
}
# items drawn with a character from the Model III ROM instead of blocks, where one reads
# as the Atari's picture: the candelabra (psi, 222), the goggles (infinity, 235), the Big
# Five logo (the letters BF) and the moneybox ($)
GLYPHS = {29: [222], 20: [235], 26: [66, 70], 32: [36]}
GLYPHNAME = {29: 'psi (candelabra)', 20: 'infinity (goggles)', 26: 'BF (the Big Five logo)', 32: '$ (moneybox)'}
out = []
w = out.append
w('; generated by tools/gen_data.py - do not edit')
w('; ---------------------------------------------------------------- screen tables')
cm=[]
for base in (0,2,4):
    for v in range(4):
        cm.append((((1 if v&2 else 0)|(2 if v&1 else 0))<<base))
w('; ---------------------------------------------------------------- sprites')
w('; Bob: 6 x 6 blocks, one byte per row, bit 7 = leftmost block')
frames = [('BOB_STAND_R', BOB['STAND']), ('BOB_WALK1_R', BOB['WALK1']), ('BOB_WALK2_R', BOB['WALK2']), ('BOB_WALK3_R', BOB['WALK3']),
          ('BOB_STAND_L', mirror(BOB['STAND'])), ('BOB_WALK1_L', mirror(BOB['WALK1'])), ('BOB_WALK2_L', mirror(BOB['WALK2'])), ('BOB_WALK3_L', mirror(BOB['WALK3'])),
          ('BOB_CLIMB1', BOB['CLIMB1']), ('BOB_CLIMB2', BOB['CLIMB2']), ('BOB_JUMP_R', BOB['JUMP']), ('BOB_JUMP_L', mirror(BOB['JUMP']))]
for name, rows in frames:
    w('%s:\tdb\t%s\t; %s' % (name, ','.join('$%02X' % b for b in rowbytes(rows)), ' '.join(rows)))
w('; Mutants: 6 x 3 blocks')
for name, rows in [('MUT_R1', MUT['R1']), ('MUT_R2', MUT['R2']), ('MUT_L1', mirror(MUT['R1'])), ('MUT_L2', mirror(MUT['R2'])), ('MUT_E1', MUT['E1']), ('MUT_E2', MUT['E2'])]:
    w('%s:\tdb\t%s\t; %s' % (name, ','.join('$%02X' % b for b in rowbytes(rows)), ' '.join(rows)))

w('; ---------------------------------------------------------------- stations')
w('; header: bob x, bob feet row, bonus (hundreds, before zone), then pointers to the lists')
w('STATIONS:\tdw\t' + ','.join('ST%d' % s for s in range(1, 11)))
for s in range(1, 11):
    st = D[str(s)]
    w('; station %d: %s' % (s, NAMES[s - 1]))
    w('ST%d:\tdb\t%d,%d,%d' % (s, st['bob']['x'], st['bob']['feet'], st['bonus']))
    w('\tdw\tST%d_RUNS,ST%d_LAD,ST%d_SLI,ST%d_ITEMS,ST%d_MUT,ST%d_SPEC' % (s, s, s, s, s, s))
    w('\tdb\t"%s",0' % NAMES[s - 1].upper())
    w('ST%d_RUNS:\t; girder runs: x, length, surface row' % s)
    for x0, n, r in st['runs']:
        if r >= 47: continue
        x0c = max(0, x0); n = min(n, 128 - x0c)
        w('\tdb\t%d,%d,%d' % (x0c, n, r))
    w('\tdb\t$FF')
    w('ST%d_LAD:\t; ladders: x (left rail), top surface row, bottom surface row' % s)
    def surf_rows(cols):
        rs = {47}
        for x0, n, r in st['runs']:
            if any(x0 <= c < x0 + n for c in cols): rs.add(r)
        return rs
    lads = sorted(st['ladders'], key=lambda l: (l[0], l[1]))
    merged = []
    for l in lads:   # stacked pieces of one ladder (the Atari's "ladder top" style) become one
        if merged and merged[-1][0] == l[0] and abs(merged[-1][2] - l[1]) <= 1 and \
           not (surf_rows([l[0] + 1, l[0] + 2]) - {47}) & {l[1] - 1, l[1], l[1] + 1, merged[-1][2]}:
            merged[-1] = (l[0], merged[-1][1], l[2])
        else:
            merged.append(tuple(l))
    for lx, top, bot in merged:
        # snap the ends to the girders Bob actually stands on there (feet columns lx+1, lx+2):
        # the Atari ladder heights round to a row below the girder's top
        rs = surf_rows([lx + 1, lx + 2])
        t2 = min(rs, key=lambda r: (abs(r - top), r > top)) if any(abs(r - top) <= 2 for r in rs) else top
        b2 = min(rs, key=lambda r: (abs(r - bot), r < bot)) if any(abs(r - bot) <= 2 for r in rs) else bot
        w('\tdb\t%d,%d,%d\t; (converted %d, %d)' % (lx, t2, b2, top, bot))
    w('\tdb\t$FF')
    w('ST%d_SLI:\t; slides: x0, y0 (feet row at the top), x1, y1' % s)
    # slides start exactly where Bob's x and feet row match (as the Atari's BOB_X/BOB_Y test):
    # 1. a slide whose top Bob cannot stand at is moved onto the girder it leaves from
    # 2. a slide ending next to the top of another is joined to it, so the chain carries on
    def supported(x, r): return r == 47 or any(x0 <= c < x0 + n and rr == r for x0, n, rr in st['runs'] for c in (x + 2, x + 3))
    sl = [list(s) for s in st['slides']]
    for sd in sl:
        x0, y0 = sd[0], sd[1]
        if supported(x0, y0): continue
        best = None
        for rx, n, r in st['runs']:
            if not (y0 - 3 <= r <= y0 + 1): continue
            e = rx + n - 1
            nx = e - 2 if e < x0 + 2 else (rx - 3 if rx > x0 + 3 else x0)
            if abs(nx - x0) <= 6 and (best is None or abs(nx - x0) + abs(r - y0) < best[0]):
                best = (abs(nx - x0) + abs(r - y0), nx, r)
        if best: sd[0], sd[1] = best[1], best[2]
    for a in sl:
        for b in sl:
            if a is not b and abs(a[3] - b[1]) <= 1 and abs(a[2] - b[0]) <= 3: a[2], a[3] = b[0], b[1]
    for x0, y0, x1, y1 in sl: w('\tdb\t%d,%d,%d,%d' % (x0, y0, x1, y1))
    w('\tdb\t$FF')
    w('ST%d_ITEMS:\t; items: x, top row, width, height, points/100, shape, then 2 bytes per row' % s)
    # what the build will have drawn, to find items whose character cell is clear
    occ = set()
    for x0, n, r in st['runs']:
        for x in range(max(0, x0), min(128, x0 + n)): occ.add((x, r)); occ.add((x, r + 1))
    for x in range(128): occ.add((x, 47))
    for lx, top, bot in st['ladders']:
        for y in range(top - 2, bot + 1):
            for x in range(lx, lx + 4): occ.add((x, y))
    for x0, y0, x1, y1 in st['slides']:
        n = max(1, y1 - y0)
        for k in range(n + 1):
            xx = x0 + (x1 - x0) * k // n
            for x in range(xx, xx + 3): occ.add((x, y0 + k))
    for it in st['items']:
        g = GLYPHS.get(it['shape'])
        if g:
            bottom = it['y'] + it['h'] - 1            # the row it rests on the girder with
            cr = (bottom + 1) // 3 - 1                # the lowest character row wholly above that
            cx = it['x'] + it['w'] // 2 - len(g)      # centred: block x of the first character
            col0 = max(0, min(63 - len(g) + 1, (cx + 1) // 2))
            ok = False
            for col, cr2 in ((col0, cr), (col0 - 1, cr), (col0 + 1, cr), (col0 - 2, cr), (col0 + 2, cr)):
                cells = {(col * 2 + dx, cr2 * 3 + dy) for dx in range(2 * len(g)) for dy in range(3)}
                if cr2 >= 1 and 0 <= col <= 64 - len(g) and not (cells & occ):
                    ok = True; cr = cr2; break
            if ok:
                w('\tdb\t%d,%d,%d,3,%d,%d,%d,%s\t; drawn with the character ROM: %s' % (col * 2, cr * 3, 2 * len(g), it['pts'], it['shape'] | 0x80, len(g), ','.join(str(c) for c in g), GLYPHNAME[it['shape']]))
                continue
        rows = []
        for row in it['img']:
            bits = ''.join('1' if v else '0' for v in row).ljust(16, '0')[:16]
            rows += [int(bits[:8], 2), int(bits[8:], 2)]
        w('\tdb\t%d,%d,%d,%d,%d,%d,%s' % (it['x'], it['y'], min(16, it['w']), it['h'], it['pts'], it['shape'], ','.join('$%02X' % b for b in rows)))
    w('\tdb\t$FF')
    w('ST%d_MUT:\t; mutants: x, feet row, min x, max x, start dir (1 / -1), step delay (Atari frames)' % s)
    for m in st['mutants']:
        x = m['x']; x2 = x + m['dx'] * m['patrol']
        lo, hi = max(0, min(x, x2)), min(122, max(x, x2))
        for rx, n, r in st['runs']:   # keep the body over the girder it walks on (1 block may overhang)
            if r == m['feet'] and rx <= x + 3 and rx + n > x + 2:
                lo2, hi2 = max(lo, rx - 1), min(hi, rx + n - 5)
                if hi2 - lo2 < 2:               # a landing too narrow for its patrol: pace across it
                    lo2, hi2 = max(0, rx - 1), min(122, rx + n - 5)
                if hi2 >= lo2: lo, hi = lo2, hi2
                break
        w('\tdb\t%d,%d,%d,%d,%d,%d' % (min(max(x, lo), hi), m['feet'], lo, hi, m['dx'] & 0xFF, max(1, m['delay'])))
    w('\tdb\t$FF')
    w('ST%d_SPEC:\t; specials, each: type, then its bytes; $FF ends' % s)
    if st['trans']:
        px = st['trans'] - 0x30
        w('\tdb\t1,%d,%d,%d,%d,47,36,24,13\t; transporter: booth x0, x1, Bob x range, floors 1-4' % (X(px - 7), X(px + 9) - 1, X(px - 5), X(px - 1)))
    for timer, wd, x, y, travel, d in st['platforms']:
        d = 1 if d < 128 else -1
        xs = X(x); xe = X(x + d * travel); tm = abs(xe - xs)
        spd = round(256 * tm * 2 / (travel * timer))
        tile = 7 if s == 8 else 9          # station 8's bar is deadly
        wait = 1 if s == 9 else 0          # station 9's wait for Bob
        w('\tdb\t2,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d\t; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits' % (xs, Ym(y), max(2, round(wd * 0.8)), tm, tm, d & 0xFF, spd & 0xFF, spd >> 8, tile, wait))
    for line in SPECIALS.get(s, []): w('\t' + line)
    w('\tdb\t$FF')
# ---- Clementine, from the Atari's TUNE table ($9D46): (AUDF divider, length) pairs, $FE ends a
# phrase, $FF the tune.  A note sounds for length + 11 frames (60 Hz) in the Atari code; pitch
# f = 21453 / (divider + 1) puts divider $28 on C5.  BEEP's cycle is 26 * B + 84 T-states.
ROMB = open(_os.path.join(REPO, 'rom/atari_miner.rom'), 'rb').read()
w('; ---------------------------------------------------------------- Clementine')
w('; TUNE: half-period loop count B, cycles (2 bytes) for the tone; 0 = phrase end (a pause); $FF = end')
tune = []
i = 0x9D46 - 0x8000
while True:
    n = ROMB[i]
    if n == 0xFF: tune.append('$FF'); break
    if n == 0xFE: tune.append('0'); i += 1; continue
    ln = ROMB[i + 1]; i += 2
    f = 21453 / (n + 1)
    B = round((2027520 / f - 84) / 26)
    cyc = round(f * (ln + 8) / 60)
    tune.append('%d,%d,%d' % (B, cyc & 255, cyc >> 8))
w('TUNE:\tdb\t' + ', '.join(tune))
# ---- the title logo: "MINER 2049er" in 5 x 7 block letters, 128 blocks wide, 7 rows
G = {
 'M': ["#...#", "##.##", "#.#.#", "#.#.#", "#...#", "#...#", "#...#"],
 'I': ["#####", "..#..", "..#..", "..#..", "..#..", "..#..", "#####"],
 'N': ["#...#", "##..#", "#.#.#", "#..##", "#...#", "#...#", "#...#"],
 'E': ["#####", "#....", "#....", "####.", "#....", "#....", "#####"],
 'R': ["####.", "#...#", "#...#", "####.", "#.#..", "#..#.", "#...#"],
 '2': [".###.", "#...#", "....#", "..##.", ".#...", "#....", "#####"],
 '0': [".###.", "#...#", "#..##", "#.#.#", "##..#", "#...#", ".###."],
 '4': ["...#.", "..##.", ".#.#.", "#..#.", "#####", "...#.", "...#."],
 '9': [".###.", "#...#", "#...#", ".####", "....#", "...#.", ".##.."],
 'e': [".....", ".....", ".###.", "#...#", "#####", "#....", ".###."],
 'r': [".....", ".....", "#.##.", "##..#", "#....", "#....", "#...."],
 ' ': ["....."] * 7,
}
word = "MINER  2049er"
rows = [''] * 7
for ch in word:
    for r in range(7): rows[r] += G[ch][r] + '.'
x0 = (128 - len(rows[0])) // 2
w('; ---------------------------------------------------------------- title logo')
w('; LOGO: 7 rows of 16 bytes (128 blocks, bit 7 = leftmost)')
for r in range(7):
    bits = ('.' * x0 + rows[r]).ljust(128, '.')[:128]
    w('\tdb\t' + ','.join('$%02X' % int(bits[k:k + 8].replace('#', '1').replace('.', '0'), 2) for k in range(0, 128, 8)) + '\t; ' + bits.rstrip('.'))
out.insert(out.index('; ---------------------------------------------------------------- title logo') + 2, 'LOGO:')
open(_os.path.join(REPO, 'src/data.asm'), 'w').write('\n'.join(out) + '\n')
# page-aligned screen tables for CELL and SPRITE (one 256-byte page each, indexed by y)
tb = ['; generated by tools/gen_data.py - page-aligned tables, indexed by block row y',
      '\tif\t$ > TABLES', '\terror\t"code runs into the tables"', '\tendif', '\torg\tTABLES',
      'YM2:\tdb\t' + ','.join(str((y % 3) * 2) for y in range(48)) + '\t; (y mod 3) * 2: first mask of the row',
      '\torg\tTABLES+$100',
      'YM4:\tdb\t' + ','.join(str((y % 3) * 4 + 0x10) for y in range(48)) + '\t; CMASK offset of the row: $10 + (y mod 3) * 4',
      '\torg\tTABLES+$200',
      'YVL:\tdb\t' + ','.join('$%02X' % ((0x3C00 + (y // 3) * 64) & 0xFF) for y in range(48)) + '\t; VRAM address of the row (low)',
      '\torg\tTABLES+$300',
      'YVH:\tdb\t' + ','.join('$%02X' % ((0x3C00 + (y // 3) * 64) >> 8) for y in range(48)) + '\t; (high)',
      '\torg\tTABLES+$400',
      'MASKS:\tdb\t1,2,4,8,16,32\t; the bit of each block in a graphics character',
      '\torg\tTABLES+$410',
      'CMASK:\tdb\t' + ','.join(str(x) for x in cm) + '\t; a pair of blocks (bit 1 left, bit 0 right) -> character bits, per row in the character']
open(_os.path.join(REPO, 'src/tables.asm'), 'w').write('\n'.join(tb) + '\n')
print('ok', len(out))
