; generated by tools/gen_data.py - do not edit
; ---------------------------------------------------------------- screen tables
; ---------------------------------------------------------------- sprites
; Bob: 6 x 6 blocks, one byte per row, bit 7 = leftmost block
BOB_STAND_R:	db	$30,$7C,$38,$78,$30,$28	; ..##.. .##### ..###. .####. ..##.. ..#.#.
BOB_WALK1_R:	db	$30,$7C,$38,$78,$30,$48	; ..##.. .##### ..###. .####. ..##.. .#..#.
BOB_WALK2_R:	db	$30,$7C,$38,$78,$30,$30	; ..##.. .##### ..###. .####. ..##.. ..##..
BOB_WALK3_R:	db	$30,$7C,$38,$78,$30,$88	; ..##.. .##### ..###. .####. ..##.. #...#.
BOB_STAND_L:	db	$30,$F8,$70,$78,$30,$50	; ..##.. #####. .###.. .####. ..##.. .#.#..
BOB_WALK1_L:	db	$30,$F8,$70,$78,$30,$48	; ..##.. #####. .###.. .####. ..##.. .#..#.
BOB_WALK2_L:	db	$30,$F8,$70,$78,$30,$30	; ..##.. #####. .###.. .####. ..##.. ..##..
BOB_WALK3_L:	db	$30,$F8,$70,$78,$30,$44	; ..##.. #####. .###.. .####. ..##.. .#...#
BOB_CLIMB1:	db	$30,$78,$B4,$78,$30,$48	; ..##.. .####. #.##.# .####. ..##.. .#..#.
BOB_CLIMB2:	db	$30,$78,$30,$FC,$30,$24	; ..##.. .####. ..##.. ###### ..##.. ..#..#
BOB_JUMP_R:	db	$30,$7C,$B8,$78,$48,$84	; ..##.. .##### #.###. .####. .#..#. #....#
BOB_JUMP_L:	db	$30,$F8,$74,$78,$48,$84	; ..##.. #####. .###.# .####. .#..#. #....#
; Mutants: 6 x 3 blocks
MUT_R1:	db	$78,$FC,$A8	; .####. ###### #.#.#.
MUT_R2:	db	$78,$FC,$54	; .####. ###### .#.#.#
MUT_L1:	db	$78,$FC,$54	; .####. ###### .#.#.#
MUT_L2:	db	$78,$FC,$A8	; .####. ###### #.#.#.
MUT_E1:	db	$B4,$78,$48	; #.##.# .####. .#..#.
MUT_E2:	db	$B4,$FC,$84	; #.##.# ###### #....#
; ---------------------------------------------------------------- stations
; header: bob x, bob feet row, bonus (hundreds, before zone), then pointers to the lists
STATIONS:	dw	ST1,ST2,ST3,ST4,ST5,ST6,ST7,ST8,ST9,ST10
; station 1: The Mine Shaft
ST1:	db	3,47,25
	dw	ST1_RUNS,ST1_LAD,ST1_SLI,ST1_ITEMS,ST1_MUT,ST1_SPEC
	db	"THE MINE SHAFT",0
ST1_RUNS:	; girder runs: x, length, surface row
	db	6,115,13
	db	9,3,18
	db	12,13,19
	db	105,13,19
	db	25,13,20
	db	92,13,20
	db	38,13,21
	db	80,12,21
	db	51,29,22
	db	57,16,28
	db	44,13,29
	db	73,13,29
	db	32,12,30
	db	86,13,30
	db	22,10,31
	db	99,13,31
	db	6,6,32
	db	112,6,32
	db	0,67,37
	db	67,13,38
	db	80,12,39
	db	92,13,40
	db	105,10,41
	db	73,55,43
	db	60,13,44
	db	9,51,45
	db	$FF
ST1_LAD:	; ladders: x (left rail), top surface row, bottom surface row
	db	28,37,45	; (converted 38, 45)
	db	36,13,21	; (converted 14, 21)
	db	42,30,37	; (converted 31, 37)
	db	63,22,28	; (converted 23, 28)
	db	89,43,47	; (converted 44, 47)
	db	97,31,40	; (converted 32, 40)
	db	103,13,20	; (converted 14, 20)
	db	$FF
ST1_SLI:	; slides: x0, y0 (feet row at the top), x1, y1
	db	$FF
ST1_ITEMS:	; items: x, top row, width, height, points/100, shape, then 2 bytes per row
	db	6,29,4,2,1,13,$F0,$00,$F0,$00
	db	51,18,6,2,1,6,$FC,$00,$F8,$00
	db	112,16,6,2,1,8,$FC,$00,$FC,$00
	db	19,8,7,3,4,21,$FE,$00,$FC,$00,$60,$00
	db	115,25,4,3,2,15,$20,$00,$20,$00,$F0,$00
	db	106,36,7,1,2,22,$FE,$00
	db	$FF
ST1_MUT:	; mutants: x, feet row, min x, max x, start dir (1 / -1), step delay (Atari frames)
	db	10,13,10,50,1,7
	db	84,13,57,84,255,5
	db	13,37,13,54,1,8
	db	101,47,0,101,255,5
	db	$FF
ST1_SPEC:	; specials, each: type, then its bytes; $FF ends
	db	$FF
; station 2: The Slides
ST2:	db	72,47,30
	dw	ST2_RUNS,ST2_LAD,ST2_SLI,ST2_ITEMS,ST2_MUT,ST2_SPEC
	db	"THE SLIDES",0
ST2_RUNS:	; girder runs: x, length, surface row
	db	0,128,8
	db	0,22,14
	db	32,22,14
	db	64,64,14
	db	100,6,21
	db	0,25,26
	db	76,52,26
	db	35,32,27
	db	11,29,39
	db	47,80,39
	db	$FF
ST2_LAD:	; ladders: x (left rail), top surface row, bottom surface row
	db	2,14,26	; (converted 15, 26)
	db	9,8,14	; (converted 9, 14)
	db	12,26,39	; (converted 27, 39)
	db	41,8,14	; (converted 9, 14)
	db	56,39,47	; (converted 40, 47)
	db	72,8,14	; (converted 9, 14)
	db	98,26,39	; (converted 28, 39)
	db	111,8,14	; (converted 9, 14)
	db	$FF
ST2_SLI:	; slides: x0, y0 (feet row at the top), x1, y1
	db	96,14,53,27
	db	37,27,77,39
	db	121,8,121,14
	db	121,14,100,21
	db	100,21,116,26
	db	116,26,116,39
	db	116,39,88,47
	db	$FF
ST2_ITEMS:	; items: x, top row, width, height, points/100, shape, then 2 bytes per row
	db	54,5,7,2,1,10,$3C,$00,$FE,$00
	db	118,4,5,3,2,17,$C8,$00,$78,$00,$88,$00
	db	96,10,8,2,2,27,$02,$00,$F2,$00
	db	48,10,8,3,2,16,$7B,$00,$18,$00,$18,$00
	db	22,22,7,2,3,12,$FE,$00,$FE,$00
	db	88,23,4,2,1,13,$F0,$00,$F0,$00
	db	43,42,7,3,4,14,$7E,$00,$18,$00,$18,$00
	db	$FF
ST2_MUT:	; mutants: x, feet row, min x, max x, start dir (1 / -1), step delay (Atari frames)
	db	13,8,13,47,1,5
	db	95,8,67,95,255,6
	db	99,21,99,101,1,6
	db	21,47,21,36,1,7
	db	117,47,62,117,255,5
	db	$FF
ST2_SPEC:	; specials, each: type, then its bytes; $FF ends
	db	$FF
; station 3: The Transporters
ST3:	db	101,47,35
	dw	ST3_RUNS,ST3_LAD,ST3_SLI,ST3_ITEMS,ST3_MUT,ST3_SPEC
	db	"THE TRANSPORTERS",0
ST3_RUNS:	; girder runs: x, length, surface row
	db	6,115,13
	db	3,32,20
	db	92,32,20
	db	44,38,24
	db	78,42,31
	db	10,35,32
	db	50,19,36
	db	3,22,39
	db	28,20,40
	db	69,23,40
	db	100,19,40
	db	$FF
ST3_LAD:	; ladders: x (left rail), top surface row, bottom surface row
	db	5,39,47	; (converted 40, 47)
	db	15,20,32	; (converted 21, 32)
	db	28,13,20	; (converted 14, 20)
	db	38,32,40	; (converted 33, 40)
	db	85,40,47	; (converted 41, 47)
	db	95,20,31	; (converted 21, 31)
	db	106,31,40	; (converted 32, 40)
	db	$FF
ST3_SLI:	; slides: x0, y0 (feet row at the top), x1, y1
	db	$FF
ST3_ITEMS:	; items: x, top row, width, height, points/100, shape, then 2 bytes per row
	db	3,15,5,3,2,17,$C8,$00,$78,$00,$88,$00
	db	104,24,2,3,1,148,1,235	; drawn with the character ROM: infinity (goggles)
	db	25,9,6,3,3,31,$78,$00,$FC,$00,$FC,$00
	db	67,42,7,1,1,19,$FC,$00
	db	112,16,8,2,2,30,$7F,$00,$1C,$00
	db	76,17,9,2,3,28,$FF,$80,$7F,$80
	db	$FF
ST3_MUT:	; mutants: x, feet row, min x, max x, start dir (1 / -1), step delay (Atari frames)
	db	21,13,21,46,1,5
	db	81,13,67,81,255,8
	db	4,20,4,28,1,6
	db	92,20,92,117,1,5
	db	26,32,26,39,1,8
	db	77,31,77,113,1,6
	db	16,47,16,121,1,7
	db	$FF
ST3_SPEC:	; specials, each: type, then its bytes; $FF ends
	db	1,53,65,55,58,47,36,24,13	; transporter: booth x0, x1, Bob x range, floors 1-4
	db	$FF
; station 4: The Lillipads
ST4:	db	8,47,40
	dw	ST4_RUNS,ST4_LAD,ST4_SLI,ST4_ITEMS,ST4_MUT,ST4_SPEC
	db	"THE LILLIPADS",0
ST4_RUNS:	; girder runs: x, length, surface row
	db	9,109,8
	db	62,6,13
	db	0,32,16
	db	37,13,16
	db	80,12,16
	db	96,23,16
	db	0,22,20
	db	68,16,20
	db	88,13,21
	db	49,16,23
	db	106,13,23
	db	42,13,26
	db	96,13,26
	db	12,10,27
	db	32,12,29
	db	79,13,29
	db	96,10,31
	db	41,16,32
	db	9,7,33
	db	63,13,33
	db	85,10,34
	db	38,16,36
	db	100,13,36
	db	16,16,39
	db	104,16,39
	db	83,13,42
	db	40,19,43
	db	67,9,44
	db	$FF
ST4_LAD:	; ladders: x (left rail), top surface row, bottom surface row
	db	2,20,47	; (converted 21, 47)
	db	18,8,16	; (converted 9, 16)
	db	108,8,16	; (converted 9, 16)
	db	$FF
ST4_SLI:	; slides: x0, y0 (feet row at the top), x1, y1
	db	$FF
ST4_ITEMS:	; items: x, top row, width, height, points/100, shape, then 2 bytes per row
	db	41,3,8,3,2,27,$02,$00,$42,$00,$FF,$00
	db	12,22,6,1,1,8,$FC,$00
	db	60,9,7,2,3,12,$FE,$00,$FE,$00
	db	67,16,6,2,2,33,$7C,$00,$38,$00
	db	115,18,7,3,3,23,$5A,$00,$FE,$00,$FE,$00
	db	115,35,7,2,5,9,$20,$00,$FA,$00
	db	32,39,2,3,5,160,1,36	; drawn with the character ROM: $ (moneybox)
	db	64,25,8,3,3,24,$67,$00,$78,$00,$38,$00
	db	$FF
ST4_MUT:	; mutants: x, feet row, min x, max x, start dir (1 / -1), step delay (Atari frames)
	db	9,8,9,57,1,5
	db	111,8,64,111,255,8
	db	50,23,50,58,1,7
	db	95,21,89,95,255,6
	db	106,36,101,106,255,5
	db	40,43,40,52,1,7
	db	120,47,0,120,255,5
	db	$FF
ST4_SPEC:	; specials, each: type, then its bytes; $FF ends
	db	$FF
; station 5: Advanced Lillipads
ST5:	db	0,47,45
	dw	ST5_RUNS,ST5_LAD,ST5_SLI,ST5_ITEMS,ST5_MUT,ST5_SPEC
	db	"ADVANCED LILLIPADS",0
ST5_RUNS:	; girder runs: x, length, surface row
	db	6,115,8
	db	6,6,11
	db	121,7,11
	db	61,7,13
	db	6,6,14
	db	114,6,16
	db	6,6,17
	db	61,7,17
	db	113,7,19
	db	6,6,20
	db	26,6,21
	db	4,13,22
	db	58,13,22
	db	113,10,22
	db	29,10,24
	db	45,7,26
	db	115,6,26
	db	17,10,27
	db	102,6,28
	db	5,10,30
	db	39,9,30
	db	61,10,30
	db	112,6,31
	db	5,7,33
	db	27,9,34
	db	63,6,34
	db	118,6,34
	db	13,10,36
	db	63,6,37
	db	108,10,37
	db	80,7,38
	db	30,13,39
	db	98,6,39
	db	49,7,40
	db	12,7,41
	db	116,6,41
	db	30,6,42
	db	60,9,42
	db	107,6,43
	db	45,10,45
	db	$FF
ST5_LAD:	; ladders: x (left rail), top surface row, bottom surface row
	db	$FF
ST5_SLI:	; slides: x0, y0 (feet row at the top), x1, y1
	db	15,8,63,22
	db	32,8,61,17
	db	46,8,61,13
	db	61,8,61,13
	db	76,8,61,13
	db	91,8,61,17
	db	108,8,60,22
	db	61,13,61,17
	db	61,17,61,22
	db	$FF
ST5_ITEMS:	; items: x, top row, width, height, points/100, shape, then 2 bytes per row
	db	38,34,9,2,2,25,$7C,$80,$FE,$00
	db	3,39,6,2,2,33,$7C,$00,$38,$00
	db	38,4,8,3,2,16,$7B,$00,$18,$00,$18,$00
	db	83,3,7,3,3,18,$7E,$00,$0C,$00,$0C,$00
	db	100,15,2,3,5,157,1,222	; drawn with the character ROM: psi (candelabra)
	db	19,16,7,2,5,9,$20,$00,$FA,$00
	db	64,3,2,3,5,160,1,36	; drawn with the character ROM: $ (moneybox)
	db	$FF
ST5_MUT:	; mutants: x, feet row, min x, max x, start dir (1 / -1), step delay (Atari frames)
	db	6,8,6,57,1,5
	db	116,8,64,116,255,7
	db	4,22,4,10,1,6
	db	12,47,12,63,1,5
	db	64,47,64,120,1,7
	db	$FF
ST5_SPEC:	; specials, each: type, then its bytes; $FF ends
	db	2,71,25,11,29,29,1,201,0,9,0	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	2,121,14,6,15,15,255,135,0,9,0	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	2,66,44,10,27,27,1,151,1,9,0	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	$FF
; station 6: Radioactive Waste
ST6:	db	7,47,50
	dw	ST6_RUNS,ST6_LAD,ST6_SLI,ST6_ITEMS,ST6_MUT,ST6_SPEC
	db	"RADIOACTIVE WASTE",0
ST6_RUNS:	; girder runs: x, length, surface row
	db	3,19,8
	db	50,16,8
	db	84,12,8
	db	108,20,8
	db	67,6,10
	db	112,16,12
	db	83,9,14
	db	48,9,15
	db	69,7,16
	db	9,13,19
	db	68,6,20
	db	88,10,20
	db	66,6,23
	db	96,7,24
	db	58,13,27
	db	83,9,28
	db	105,16,30
	db	42,10,31
	db	26,6,34
	db	68,6,35
	db	87,6,35
	db	13,7,38
	db	108,9,38
	db	0,6,41
	db	121,7,41
	db	0,6,44
	db	121,7,45
	db	$FF
ST6_LAD:	; ladders: x (left rail), top surface row, bottom surface row
	db	12,8,19	; (converted 9, 19)
	db	114,12,30	; (converted 13, 30)
	db	$FF
ST6_SLI:	; slides: x0, y0 (feet row at the top), x1, y1
	db	$FF
ST6_ITEMS:	; items: x, top row, width, height, points/100, shape, then 2 bytes per row
	db	108,34,7,1,3,12,$FE,$00
	db	96,3,7,1,1,10,$FE,$00
	db	48,10,9,2,2,25,$7C,$80,$FE,$00
	db	12,4,6,2,2,33,$7C,$00,$38,$00
	db	24,13,4,2,1,13,$F0,$00,$F0,$00
	db	92,31,6,2,1,6,$FC,$00,$F8,$00
	db	12,29,8,2,2,27,$02,$00,$F2,$00
	db	$FF
ST6_MUT:	; mutants: x, feet row, min x, max x, start dir (1 / -1), step delay (Atari frames)
	db	3,8,3,15,1,5
	db	108,8,108,120,1,7
	db	42,31,42,45,1,6
	db	120,41,120,122,1,6
	db	$FF
ST6_SPEC:	; specials, each: type, then its bytes; $FF ends
	db	2,20,22,5,87,87,1,103,0,9,0	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	3,16,39,111,46,7	; box of radioactive waste: x0, y0, x1, y1, tile (deadly)
	db	4,13,29,"DANGER",0	; text: character row, column
	db	4,14,24,"RADIOACTIVE WASTE",0
	db	$FF
; station 7: Advanced Transporters
ST7:	db	0,47,55
	dw	ST7_RUNS,ST7_LAD,ST7_SLI,ST7_ITEMS,ST7_MUT,ST7_SPEC
	db	"ADVANCED TRANSPORTERS",0
ST7_RUNS:	; girder runs: x, length, surface row
	db	99,29,8
	db	6,22,13
	db	64,16,13
	db	118,6,13
	db	56,7,17
	db	92,7,18
	db	103,6,20
	db	69,13,21
	db	118,6,22
	db	103,6,23
	db	3,22,24
	db	45,16,24
	db	112,7,26
	db	120,6,29
	db	86,13,32
	db	112,12,33
	db	45,10,35
	db	83,13,35
	db	6,22,36
	db	63,3,36
	db	66,6,37
	db	63,9,41
	db	115,13,41
	db	49,7,42
	db	93,10,42
	db	$FF
ST7_LAD:	; ladders: x (left rail), top surface row, bottom surface row
	db	$FF
ST7_SLI:	; slides: x0, y0 (feet row at the top), x1, y1
	db	12,13,47,24
	db	47,24,84,35
	db	114,8,75,21
	db	75,21,116,33
	db	103,8,118,13
	db	118,13,118,22
	db	118,22,89,32
	db	89,32,119,41
	db	119,41,119,47
	db	$FF
ST7_ITEMS:	; items: x, top row, width, height, points/100, shape, then 2 bytes per row
	db	32,30,8,3,2,30,$FF,$00,$1C,$00,$08,$00
	db	76,37,7,1,1,19,$FC,$00
	db	44,16,9,2,3,28,$FF,$80,$7F,$80
	db	73,3,8,2,11,26,$F7,$00,$94,$00
	db	0,18,5,3,2,17,$C8,$00,$78,$00,$88,$00
	db	82,24,2,3,1,148,1,235	; drawn with the character ROM: infinity (goggles)
	db	105,40,6,2,3,31,$54,$00,$FC,$00
	db	$FF
ST7_MUT:	; mutants: x, feet row, min x, max x, start dir (1 / -1), step delay (Atari frames)
	db	64,13,64,74,1,6
	db	22,36,6,22,255,6
	db	24,47,24,63,1,5
	db	6,47,6,62,1,8
	db	$FF
ST7_SPEC:	; specials, each: type, then its bytes; $FF ends
	db	1,9,21,11,14,47,36,24,13	; transporter: booth x0, x1, Bob x range, floors 1-4
	db	2,25,11,3,64,64,1,137,0,9,0	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	2,24,26,4,17,17,1,104,0,9,0	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	2,26,37,4,15,15,1,135,0,9,0	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	2,31,45,4,60,60,1,102,0,9,0	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	$FF
; station 8: The Lift
ST8:	db	103,40,40
	dw	ST8_RUNS,ST8_LAD,ST8_SLI,ST8_ITEMS,ST8_MUT,ST8_SPEC
	db	"THE LIFT",0
ST8_RUNS:	; girder runs: x, length, surface row
	db	0,128,8
	db	0,16,16
	db	44,48,16
	db	0,41,23
	db	100,7,23
	db	112,16,23
	db	102,10,27
	db	0,41,30
	db	102,26,40
	db	0,32,41
	db	$FF
ST8_LAD:	; ladders: x (left rail), top surface row, bottom surface row
	db	9,8,16	; (converted 9, 16)
	db	47,8,16	; (converted 9, 16)
	db	60,16,23	; (converted 17, 23)
	db	114,23,40	; (converted 24, 40)
	db	121,8,23	; (converted 9, 23)
	db	$FF
ST8_SLI:	; slides: x0, y0 (feet row at the top), x1, y1
	db	73,8,73,16
	db	3,16,3,23
	db	83,16,104,23
	db	104,23,105,27
	db	3,30,3,41
	db	$FF
ST8_ITEMS:	; items: x, top row, width, height, points/100, shape, then 2 bytes per row
	db	32,3,8,2,2,27,$02,$00,$F2,$00
	db	91,3,6,2,2,33,$7C,$00,$38,$00
	db	40,17,8,3,3,24,$67,$00,$78,$00,$38,$00
	db	1,24,7,3,5,9,$20,$00,$A2,$00,$FE,$00
	db	41,24,7,1,1,10,$FE,$00
	db	111,14,5,3,2,17,$C8,$00,$78,$00,$88,$00
	db	$FF
ST8_MUT:	; mutants: x, feet row, min x, max x, start dir (1 / -1), step delay (Atari frames)
	db	2,8,2,71,1,3
	db	120,8,64,120,255,2
	db	1,23,1,34,1,4
	db	6,30,6,31,1,5
	db	25,41,5,25,255,1
	db	$FF
ST8_SPEC:	; specials, each: type, then its bytes; $FF ends
	db	2,1,43,41,84,84,1,154,1,7,0	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	5,89,40,44,89,22,44	; the lift: x, row, x range, row range
	db	$FF
; station 9: The Pulverizers
ST9:	db	121,7,60
	dw	ST9_RUNS,ST9_LAD,ST9_SLI,ST9_ITEMS,ST9_MUT,ST9_SPEC
	db	"THE PULVERIZERS",0
ST9_RUNS:	; girder runs: x, length, surface row
	db	0,22,7
	db	105,23,7
	db	0,22,13
	db	104,19,13
	db	0,22,19
	db	104,16,19
	db	0,22,25
	db	103,16,25
	db	0,22,30
	db	105,19,30
	db	0,22,36
	db	105,23,36
	db	$FF
ST9_LAD:	; ladders: x (left rail), top surface row, bottom surface row
	db	109,19,25	; (converted 20, 25)
	db	112,25,30	; (converted 26, 30)
	db	113,13,19	; (converted 14, 19)
	db	117,7,13	; (converted 9, 13)
	db	117,30,36	; (converted 32, 36)
	db	121,36,47	; (converted 37, 47)
	db	$FF
ST9_SLI:	; slides: x0, y0 (feet row at the top), x1, y1
	db	19,7,24,47
	db	19,13,24,47
	db	19,19,24,47
	db	19,25,24,47
	db	19,30,24,47
	db	19,36,24,47
	db	$FF
ST9_ITEMS:	; items: x, top row, width, height, points/100, shape, then 2 bytes per row
	db	108,42,7,1,1,19,$FC,$00
	db	13,41,5,3,2,17,$C8,$00,$78,$00,$88,$00
	db	35,33,6,1,1,8,$FC,$00
	db	35,5,6,2,1,6,$FC,$00,$F8,$00
	db	35,10,7,3,4,14,$7E,$00,$18,$00,$18,$00
	db	35,16,8,3,2,16,$7B,$00,$18,$00,$18,$00
	db	35,22,9,1,2,25,$FE,$00
	db	35,28,7,1,3,12,$FE,$00
	db	$FF
ST9_MUT:	; mutants: x, feet row, min x, max x, start dir (1 / -1), step delay (Atari frames)
	db	1,7,1,15,1,3
	db	16,13,2,16,255,3
	db	1,19,1,15,1,3
	db	16,25,2,16,255,3
	db	1,30,1,15,1,3
	db	16,36,2,16,255,3
	db	3,47,3,16,1,6
	db	112,47,36,112,255,8
	db	$FF
ST9_SPEC:	; specials, each: type, then its bytes; $FF ends
	db	2,103,9,3,82,82,255,156,1,9,1	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	2,101,15,3,80,80,255,154,1,9,1	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	2,101,21,3,80,80,255,154,1,9,1	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	2,100,26,3,79,79,255,153,1,9,1	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	2,103,32,3,82,82,255,156,1,9,1	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	2,103,38,3,82,82,255,156,1,9,1	; platform: x, row, width, steps left, travel, dir, speed/256, tile, waits
	db	6,38,32,104,39,44,35,54,73,92	; pulverizers: beam row, beam x0, x1, head top rows, head x
	db	$FF
; station 10: The Cannon
ST10:	db	117,47,65
	dw	ST10_RUNS,ST10_LAD,ST10_SLI,ST10_ITEMS,ST10_MUT,ST10_SPEC
	db	"THE CANNON",0
ST10_RUNS:	; girder runs: x, length, surface row
	db	0,67,9
	db	86,42,9
	db	0,67,19
	db	86,42,19
	db	44,23,29
	db	86,42,29
	db	1,35,31
	db	35,6,34
	db	97,23,35
	db	1,35,36
	db	35,6,39
	db	1,35,41
	db	34,6,44
	db	$FF
ST10_LAD:	; ladders: x (left rail), top surface row, bottom surface row
	db	113,35,47	; (converted 36, 47)
	db	$FF
ST10_SLI:	; slides: x0, y0 (feet row at the top), x1, y1
	db	11,9,43,19
	db	43,19,43,47
	db	43,29,43,47
	db	112,9,112,35
	db	112,19,112,35
	db	112,29,112,35
	db	$FF
ST10_ITEMS:	; items: x, top row, width, height, points/100, shape, then 2 bytes per row
	db	3,28,6,3,3,34,$38,$00,$78,$00,$EC,$00
	db	12,28,6,3,3,34,$38,$00,$78,$00,$EC,$00
	db	22,28,6,3,3,34,$38,$00,$78,$00,$EC,$00
	db	3,33,6,3,3,34,$38,$00,$78,$00,$EC,$00
	db	12,33,6,3,3,34,$38,$00,$78,$00,$EC,$00
	db	22,33,6,3,3,34,$38,$00,$78,$00,$EC,$00
	db	3,39,6,1,2,35,$EC,$00
	db	12,39,6,1,2,35,$EC,$00
	db	22,39,6,1,2,35,$EC,$00
	db	3,44,4,2,1,36,$30,$00,$30,$00
	db	12,44,4,2,1,36,$30,$00,$30,$00
	db	22,44,4,2,1,36,$30,$00,$30,$00
	db	$FF
ST10_MUT:	; mutants: x, feet row, min x, max x, start dir (1 / -1), step delay (Atari frames)
	db	0,9,0,60,1,7
	db	118,9,86,118,255,6
	db	61,19,1,61,255,8
	db	87,19,87,122,1,7
	db	62,29,45,62,255,10
	db	86,29,86,119,1,9
	db	$FF
ST10_SPEC:	; specials, each: type, then its bytes; $FF ends
	db	3,0,24,41,24,10	; the TNT store: roof (a row higher than the Atari line, so Bob
	db	3,0,25,0,46,10	;   fits under it on the top shelf), walls (tile 10 = wall)
	db	3,41,25,41,40,10
	db	3,15,21,15,23,10	; its sign, under the girder above
	db	3,26,21,26,23,10
	db	4,7,9,"TNT",0
	db	7,90,51,90,29,19,9	; the cannon: rest x, x range, landing rows for 1-3 tons
	db	$FF
; ---------------------------------------------------------------- Clementine
; TUNE: half-period loop count B, cycles (2 bytes) for the tone; 0 = phrase end (a pause); $FF = end
TUNE:	db	146,122,0, 146,87,0, 146,105,0, 193,79,0, 113,156,0, 113,112,0, 113,134,0, 146,105,0, 146,122,0, 113,112,0, 95,159,0, 95,159,0, 106,167,0, 113,112,0, 128,159,0, 0, 128,139,0, 113,112,0, 106,143,0, 106,143,0, 113,156,0, 128,99,0, 113,134,0, 146,105,0, 146,122,0, 113,112,0, 128,119,0, 193,79,0, 153,116,0, 128,99,0, 146,140,0, $FF
; ---------------------------------------------------------------- title logo
; LOGO: 7 rows of 16 bytes (128 blocks, bit 7 = leftmost)
LOGO:
	db	$00,$00,$00,$45,$F4,$5F,$78,$00,$0E,$38,$23,$80,$00,$00,$00,$00	; .........................#...#.#####.#...#.#####.####...............###...###.....#...###
	db	$00,$00,$00,$6C,$46,$50,$44,$00,$11,$44,$64,$40,$00,$00,$00,$00	; .........................##.##...#...##..#.#.....#...#.............#...#.#...#...##..#...#
	db	$00,$00,$00,$54,$45,$50,$44,$00,$01,$4C,$A4,$4E,$58,$00,$00,$00	; .........................#.#.#...#...#.#.#.#.....#...#.................#.#..##..#.#..#...#..###..#.##
	db	$00,$00,$00,$54,$44,$DE,$78,$00,$06,$55,$23,$D1,$64,$00,$00,$00	; .........................#.#.#...#...#..##.####..####................##..#.#.#.#..#...####.#...#.##..#
	db	$00,$00,$00,$44,$44,$50,$50,$00,$08,$65,$F0,$5F,$40,$00,$00,$00	; .........................#...#...#...#...#.#.....#.#................#....##..#.#####.....#.#####.#
	db	$00,$00,$00,$44,$44,$50,$48,$00,$10,$44,$20,$90,$40,$00,$00,$00	; .........................#...#...#...#...#.#.....#..#..............#.....#...#....#.....#..#.....#
	db	$00,$00,$00,$45,$F4,$5F,$44,$00,$1F,$38,$23,$0E,$40,$00,$00,$00	; .........................#...#.#####.#...#.#####.#...#.............#####..###.....#...##....###..#
