; generated by tools/gen_data.py - page-aligned tables, indexed by block row y
	if	$ > TABLES
	error	"code runs into the tables"
	endif
	org	TABLES
YM2:	db	0,2,4,0,2,4,0,2,4,0,2,4,0,2,4,0,2,4,0,2,4,0,2,4,0,2,4,0,2,4,0,2,4,0,2,4,0,2,4,0,2,4,0,2,4,0,2,4	; (y mod 3) * 2: first mask of the row
	org	TABLES+$100
YM4:	db	16,20,24,16,20,24,16,20,24,16,20,24,16,20,24,16,20,24,16,20,24,16,20,24,16,20,24,16,20,24,16,20,24,16,20,24,16,20,24,16,20,24,16,20,24,16,20,24	; CMASK offset of the row: $10 + (y mod 3) * 4
	org	TABLES+$200
YVL:	db	$00,$00,$00,$40,$40,$40,$80,$80,$80,$C0,$C0,$C0,$00,$00,$00,$40,$40,$40,$80,$80,$80,$C0,$C0,$C0,$00,$00,$00,$40,$40,$40,$80,$80,$80,$C0,$C0,$C0,$00,$00,$00,$40,$40,$40,$80,$80,$80,$C0,$C0,$C0	; VRAM address of the row (low)
	org	TABLES+$300
YVH:	db	$3C,$3C,$3C,$3C,$3C,$3C,$3C,$3C,$3C,$3C,$3C,$3C,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F	; (high)
	org	TABLES+$400
MASKS:	db	1,2,4,8,16,32	; the bit of each block in a graphics character
	org	TABLES+$410
CMASK:	db	0,2,1,3,0,8,4,12,0,32,16,48	; a pair of blocks (bit 1 left, bit 0 right) -> character bits, per row in the character
